'use client'

/**
 * DEV SPIKE — Inner component (client-only, loaded via dynamic import)
 *
 * @cantoo/pdf-lib v2.7 evaluation:
 *   A. AcroForm fill + flatten
 *   B. Free-position text overlay with screen→PDF coordinate transform
 *   C. Photo/image embed
 *
 * Sample PDFs:
 *   /spike/fw9-fillable.pdf  — SYNTHETIC AcroForm (generated by this code at runtime
 *                              if the real IRS W-9 fetch fails; clearly labelled).
 *   /spike/flat-sample.pdf   — SYNTHETIC flat PDF (always generated; no real fetch).
 *
 * The spike attempts to fetch a real IRS W-9 from:
 *   https://www.irs.gov/pub/irs-pdf/fw9.pdf
 * If that fetch fails (CORS/network), a synthetic AcroForm is used instead.
 * Status is displayed in the banner on screen.
 */

import React, {
  useState,
  useRef,
  useCallback,
  useEffect,
} from 'react'
import { Document, Page, pdfjs } from 'react-pdf'
import 'react-pdf/dist/Page/AnnotationLayer.css'
import 'react-pdf/dist/Page/TextLayer.css'
import {
  PDFDocument as CantooDocument,
  StandardFonts as CantooStandardFonts,
  rgb as cantooRgb,
  type PDFFont,
} from '@cantoo/pdf-lib'

// Mirror the established project worker config
pdfjs.GlobalWorkerOptions.workerSrc = '/pdf.worker.min.mjs'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
interface OverlayPoint {
  cssX: number
  cssY: number
  text: string
}

interface TransformDebug {
  rawClickX: number
  rawClickY: number
  scale: number
  dpr: number
  pdfX: number
  pdfY: number
  pdfPageWidth: number
  pdfPageHeight: number
}

type SamplePdfSource = 'real-irs' | 'synthetic' | 'loading'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Build a minimal synthetic AcroForm PDF using @cantoo/pdf-lib.
 *
 * Creates a single-page PDF with three text fields:
 *   - first_name (visible label + field box)
 *   - last_name
 *   - address
 *
 * This is the fallback when the real IRS W-9 cannot be fetched.
 */
async function buildSyntheticAcroFormPdf(): Promise<Uint8Array> {
  const doc = await CantooDocument.create()
  const page = doc.addPage([612, 792]) // US Letter
  const font = await doc.embedFont(CantooStandardFonts.Helvetica)
  const form = doc.getForm()

  // Title
  page.drawText('SYNTHETIC FILLABLE FORM (spike stand-in for IRS W-9)', {
    x: 40,
    y: 740,
    size: 10,
    font,
    color: cantooRgb(0.6, 0.1, 0.1),
  })
  page.drawText('DEV SPIKE — @cantoo/pdf-lib AcroForm test', {
    x: 40,
    y: 724,
    size: 8,
    font,
    color: cantooRgb(0.4, 0.4, 0.4),
  })

  // Field: first_name
  page.drawText('First Name:', { x: 40, y: 680, size: 10, font, color: cantooRgb(0, 0, 0) })
  const firstNameField = form.createTextField('first_name')
  firstNameField.addToPage(page, { x: 120, y: 668, width: 200, height: 20 })

  // Field: last_name
  page.drawText('Last Name:', { x: 40, y: 640, size: 10, font, color: cantooRgb(0, 0, 0) })
  const lastNameField = form.createTextField('last_name')
  lastNameField.addToPage(page, { x: 120, y: 628, width: 200, height: 20 })

  // Field: address
  page.drawText('Address:', { x: 40, y: 600, size: 10, font, color: cantooRgb(0, 0, 0) })
  const addressField = form.createTextField('address')
  addressField.enableMultiline()
  addressField.addToPage(page, { x: 120, y: 568, width: 300, height: 40 })

  // Field: ssn (masked)
  page.drawText('SSN:', { x: 40, y: 540, size: 10, font, color: cantooRgb(0, 0, 0) })
  const ssnField = form.createTextField('ssn')
  ssnField.addToPage(page, { x: 120, y: 528, width: 160, height: 20 })

  // Instructions area
  page.drawRectangle({
    x: 40,
    y: 100,
    width: 532,
    height: 400,
    borderColor: cantooRgb(0.8, 0.8, 0.8),
    borderWidth: 1,
  })
  page.drawText('[ Intentionally blank — content area ]', {
    x: 180,
    y: 295,
    size: 9,
    font,
    color: cantooRgb(0.7, 0.7, 0.7),
  })

  return doc.save()
}

/**
 * Build a minimal synthetic FLAT (non-fillable) PDF.
 */
async function buildSyntheticFlatPdf(): Promise<Uint8Array> {
  const doc = await CantooDocument.create()
  const page = doc.addPage([612, 792])
  const font = await doc.embedFont(CantooStandardFonts.Helvetica)

  page.drawText('SYNTHETIC FLAT PDF (spike stand-in)', {
    x: 40,
    y: 740,
    size: 10,
    font,
    color: cantooRgb(0.6, 0.1, 0.1),
  })
  page.drawText('DEV SPIKE — @cantoo/pdf-lib flat PDF render test', {
    x: 40,
    y: 724,
    size: 8,
    font,
    color: cantooRgb(0.4, 0.4, 0.4),
  })

  // Simulated body text
  const lines = [
    'This PDF has no AcroForm fields.',
    'It is used to verify that pdfjs renders flat PDFs correctly',
    'alongside fillable forms, and that drawText positions land',
    'accurately on export.',
    '',
    'Verify: the text below this line should be exactly 1 line-height lower.',
    '— Line A (y = 600 in PDF coords)',
  ]
  let y = 680
  for (const line of lines) {
    page.drawText(line, { x: 40, y, size: 10, font, color: cantooRgb(0, 0, 0) })
    y -= 18
  }

  // Grid lines for coordinate debugging
  for (let gridY = 100; gridY <= 700; gridY += 50) {
    page.drawLine({
      start: { x: 40, y: gridY },
      end: { x: 572, y: gridY },
      thickness: 0.5,
      color: cantooRgb(0.85, 0.85, 0.95),
    })
    page.drawText(String(gridY), {
      x: 576,
      y: gridY - 4,
      size: 7,
      font,
      color: cantooRgb(0.5, 0.5, 0.7),
    })
  }

  return doc.save()
}

/**
 * Screen→PDF coordinate transform.
 *
 * The pdfjs canvas is rendered at CSS size canvasCSSWidth × canvasCSSHeight.
 * The PDF page coordinate system has origin at bottom-left.
 *
 * Steps:
 *   1. Get click position in CSS pixels relative to canvas top-left edge.
 *   2. scale = canvasCSSWidth / pdfPageWidth  (same ratio used when pdfjs rendered)
 *   3. pdfX = cssX / scale
 *   4. pdfY = pdfPageHeight - (cssY / scale)  ← flip: CSS top-down → PDF bottom-up
 *
 * DPR note: getBoundingClientRect() returns CSS pixels. The underlying canvas may
 * have canvas.width = cssWidth * dpr for crispness, but layout positions are always
 * in CSS pixels. So DPR cancels out and does NOT appear in the formula.
 */
function screenToPdf(
  clickCssX: number,
  clickCssY: number,
  canvasCssWidth: number,
  pdfPageWidth: number,
  pdfPageHeight: number,
): { pdfX: number; pdfY: number; scale: number } {
  const scale = canvasCssWidth / pdfPageWidth
  const pdfX = clickCssX / scale
  const pdfY = pdfPageHeight - clickCssY / scale
  return { pdfX, pdfY, scale }
}

/**
 * Coerce a Uint8Array (which may carry ArrayBufferLike from cantoo types) to a
 * plain ArrayBuffer-backed Uint8Array accepted by the Blob constructor.
 */
function toPlainUint8Array(bytes: Uint8Array): Uint8Array<ArrayBuffer> {
  return new Uint8Array(bytes) as Uint8Array<ArrayBuffer>
}

/**
 * Download a Uint8Array as a PDF file.
 */
function downloadPdf(bytes: Uint8Array, filename: string) {
  const blob = new Blob([toPlainUint8Array(bytes)], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ---------------------------------------------------------------------------
// Main spike component
// ---------------------------------------------------------------------------
export default function SpikePdfInner() {
  // ── PDF bytes state ──────────────────────────────────────────────────────
  const [acroformPdfBytes, setAcroformPdfBytes] = useState<Uint8Array | null>(null)
  const [flatPdfBytes, setFlatPdfBytes] = useState<Uint8Array | null>(null)
  const [acroformSource, setAcroformSource] = useState<SamplePdfSource>('loading')

  // ── Test A: AcroForm fill results ────────────────────────────────────────
  const [acroFieldNames, setAcroFieldNames] = useState<string[]>([])
  const [acroFillResult, setAcroFillResult] = useState<Uint8Array | null>(null)
  const [acroFillError, setAcroFillError] = useState<string | null>(null)
  const [acroFillRunning, setAcroFillRunning] = useState(false)

  // ── Test B: Free-position overlay ────────────────────────────────────────
  const [overlayPoints, setOverlayPoints] = useState<OverlayPoint[]>([])
  const [pendingOverlayText, setPendingOverlayText] = useState('Sample Text')
  const [overlayResult, setOverlayResult] = useState<Uint8Array | null>(null)
  const [overlayRunning, setOverlayRunning] = useState(false)
  const [overlayError, setOverlayError] = useState<string | null>(null)
  const [transformDebug, setTransformDebug] = useState<TransformDebug | null>(null)
  const [overlayPlacementMode, setOverlayPlacementMode] = useState(false)

  // Page render dimensions for B transform
  const flatPageRef = useRef<HTMLDivElement>(null)
  const [flatPageDims, setFlatPageDims] = useState<{ cssWidth: number; cssHeight: number; pdfWidth: number; pdfHeight: number } | null>(null)

  // ── Test C: Image embed ──────────────────────────────────────────────────
  const [imageEmbedResult, setImageEmbedResult] = useState<Uint8Array | null>(null)
  const [imageEmbedRunning, setImageEmbedRunning] = useState(false)
  const [imageEmbedError, setImageEmbedError] = useState<string | null>(null)
  const [imagePreviewUrl, setImagePreviewUrl] = useState<string | null>(null)

  // ── Initialization ───────────────────────────────────────────────────────
  useEffect(() => {
    void (async () => {
      // Always build synthetic flat PDF
      const flatBytes = await buildSyntheticFlatPdf()
      setFlatPdfBytes(flatBytes)

      // Try real IRS W-9; fall back to synthetic
      try {
        const res = await fetch('/spike/fw9-fillable.pdf')
        if (res.ok) {
          const buf = await res.arrayBuffer()
          setAcroformPdfBytes(new Uint8Array(buf))
          setAcroformSource('real-irs')
          return
        }
      } catch {
        // fall through to synthetic
      }
      const synth = await buildSyntheticAcroFormPdf()
      setAcroformPdfBytes(synth)
      setAcroformSource('synthetic')
    })()
  }, [])

  // ── Test A: detect fields ────────────────────────────────────────────────
  useEffect(() => {
    if (!acroformPdfBytes) return
    void (async () => {
      try {
        const doc = await CantooDocument.load(acroformPdfBytes, { ignoreEncryption: true })
        const form = doc.getForm()
        const fields = form.getFields()
        setAcroFieldNames(fields.map(f => f.getName()))
      } catch (e) {
        setAcroFieldNames([`Error detecting fields: ${e instanceof Error ? e.message : String(e)}`])
      }
    })()
  }, [acroformPdfBytes])

  // ── Test A: fill + flatten ────────────────────────────────────────────────
  const handleAcroFill = useCallback(async () => {
    if (!acroformPdfBytes) return
    setAcroFillRunning(true)
    setAcroFillError(null)
    setAcroFillResult(null)
    try {
      const doc = await CantooDocument.load(acroformPdfBytes, { ignoreEncryption: true })
      const form = doc.getForm()
      const fields = form.getFields()

      // Fill the first two text fields with test values
      let filled = 0
      for (const field of fields) {
        if (filled >= 2) break
        try {
          // getTextField throws if wrong type
          const tf = form.getTextField(field.getName())
          const testValues = ['Jane Doe', '123 Elm Street, Burlington VT 05401', '(802) 555-0100', '000-00-0000']
          tf.setText(testValues[filled] ?? `Test value ${filled + 1}`)
          filled++
        } catch {
          // field is not a text field — skip
        }
      }

      form.flatten()
      const saved = await doc.save()
      setAcroFillResult(saved)
    } catch (e) {
      setAcroFillError(e instanceof Error ? e.message : String(e))
    } finally {
      setAcroFillRunning(false)
    }
  }, [acroformPdfBytes])

  // ── Test B: canvas click handler ─────────────────────────────────────────
  const handleFlatCanvasClick = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (!overlayPlacementMode || !flatPageDims) return
    const rect = e.currentTarget.getBoundingClientRect()
    const cssX = e.clientX - rect.left
    const cssY = e.clientY - rect.top
    const { pdfX, pdfY, scale } = screenToPdf(cssX, cssY, flatPageDims.cssWidth, flatPageDims.pdfWidth, flatPageDims.pdfHeight)
    const dpr = window.devicePixelRatio ?? 1

    setTransformDebug({
      rawClickX: Math.round(cssX * 100) / 100,
      rawClickY: Math.round(cssY * 100) / 100,
      scale: Math.round(scale * 1000) / 1000,
      dpr,
      pdfX: Math.round(pdfX * 100) / 100,
      pdfY: Math.round(pdfY * 100) / 100,
      pdfPageWidth: flatPageDims.pdfWidth,
      pdfPageHeight: flatPageDims.pdfHeight,
    })

    setOverlayPoints(prev => [...prev, { cssX, cssY, text: pendingOverlayText }])
  }, [overlayPlacementMode, flatPageDims, pendingOverlayText])

  // ── Test B: export overlay PDF ───────────────────────────────────────────
  const handleOverlayExport = useCallback(async () => {
    if (!flatPdfBytes || !flatPageDims || overlayPoints.length === 0) return
    setOverlayRunning(true)
    setOverlayError(null)
    setOverlayResult(null)
    try {
      const doc = await CantooDocument.load(flatPdfBytes)
      const pages = doc.getPages()
      const page = pages[0]
      const font: PDFFont = await doc.embedFont(CantooStandardFonts.Helvetica)
      const { width: pdfW, height: pdfH } = page.getSize()

      for (const pt of overlayPoints) {
        const { pdfX, pdfY } = screenToPdf(pt.cssX, pt.cssY, flatPageDims.cssWidth, pdfW, pdfH)
        page.drawText(pt.text, {
          x: pdfX,
          y: pdfY,
          size: 12,
          font,
          color: cantooRgb(0, 0, 0.8),
        })
      }

      const saved = await doc.save()
      setOverlayResult(saved)
    } catch (e) {
      setOverlayError(e instanceof Error ? e.message : String(e))
    } finally {
      setOverlayRunning(false)
    }
  }, [flatPdfBytes, flatPageDims, overlayPoints])

  // ── Test C: image embed ───────────────────────────────────────────────────
  const handleImageFile = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    setImageEmbedRunning(true)
    setImageEmbedError(null)
    setImageEmbedResult(null)
    setImagePreviewUrl(null)

    // Preview
    const previewUrl = URL.createObjectURL(file)
    setImagePreviewUrl(previewUrl)

    try {
      const arrayBuf = await file.arrayBuffer()
      const imgBytes = new Uint8Array(arrayBuf)
      const doc = await CantooDocument.create()
      const page = doc.addPage([612, 792])
      const font = await doc.embedFont(CantooStandardFonts.Helvetica)

      let embedImage
      const isJpeg = file.type === 'image/jpeg' || file.name.toLowerCase().endsWith('.jpg') || file.name.toLowerCase().endsWith('.jpeg')
      if (isJpeg) {
        embedImage = await doc.embedJpg(imgBytes)
      } else {
        // png or treat as png
        embedImage = await doc.embedPng(imgBytes)
      }

      // Scale image to fit page with 40px margin
      const margin = 40
      const maxW = 612 - margin * 2
      const maxH = 792 - margin * 2
      const ratio = Math.min(maxW / embedImage.width, maxH / embedImage.height)
      const drawW = embedImage.width * ratio
      const drawH = embedImage.height * ratio
      const drawX = (612 - drawW) / 2
      const drawY = (792 - drawH) / 2

      page.drawImage(embedImage, { x: drawX, y: drawY, width: drawW, height: drawH })
      page.drawText(`${file.name} — embedded via ${isJpeg ? 'embedJpg' : 'embedPng'} — DEV SPIKE`, {
        x: margin,
        y: margin - 12,
        size: 7,
        font,
        color: cantooRgb(0.5, 0.5, 0.5),
      })

      const saved = await doc.save()
      setImageEmbedResult(saved)
    } catch (e) {
      setImageEmbedError(e instanceof Error ? e.message : String(e))
    } finally {
      setImageEmbedRunning(false)
    }
  }, [])

  // ── Render helpers ────────────────────────────────────────────────────────
  const acroformBlobUrl = useRef<string>('')
  const flatBlobUrl = useRef<string>('')
  const acroFillBlobUrl = useRef<string>('')
  const overlayBlobUrl = useRef<string>('')

  const [acroformViewUrl, setAcroformViewUrl] = useState('')
  const [flatViewUrl, setFlatViewUrl] = useState('')
  const [acroFillViewUrl, setAcroFillViewUrl] = useState('')
  const [overlayViewUrl, setOverlayViewUrl] = useState('')

  useEffect(() => {
    if (!acroformPdfBytes) return
    if (acroformBlobUrl.current) URL.revokeObjectURL(acroformBlobUrl.current)
    acroformBlobUrl.current = URL.createObjectURL(new Blob([toPlainUint8Array(acroformPdfBytes)], { type: 'application/pdf' }))
    setAcroformViewUrl(acroformBlobUrl.current)
  }, [acroformPdfBytes])

  useEffect(() => {
    if (!flatPdfBytes) return
    if (flatBlobUrl.current) URL.revokeObjectURL(flatBlobUrl.current)
    flatBlobUrl.current = URL.createObjectURL(new Blob([toPlainUint8Array(flatPdfBytes)], { type: 'application/pdf' }))
    setFlatViewUrl(flatBlobUrl.current)
  }, [flatPdfBytes])

  useEffect(() => {
    if (!acroFillResult) return
    if (acroFillBlobUrl.current) URL.revokeObjectURL(acroFillBlobUrl.current)
    acroFillBlobUrl.current = URL.createObjectURL(new Blob([toPlainUint8Array(acroFillResult)], { type: 'application/pdf' }))
    setAcroFillViewUrl(acroFillBlobUrl.current)
  }, [acroFillResult])

  useEffect(() => {
    if (!overlayResult) return
    if (overlayBlobUrl.current) URL.revokeObjectURL(overlayBlobUrl.current)
    overlayBlobUrl.current = URL.createObjectURL(new Blob([toPlainUint8Array(overlayResult)], { type: 'application/pdf' }))
    setOverlayViewUrl(overlayBlobUrl.current)
  }, [overlayResult])

  // ── JSX ───────────────────────────────────────────────────────────────────
  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', padding: '0', background: '#f5f4f0', minHeight: '100vh' }}>

      {/* DEV SPIKE BANNER */}
      <div style={{
        background: '#7c1d1d',
        color: '#fff',
        padding: '10px 24px',
        fontSize: 13,
        fontWeight: 600,
        letterSpacing: '0.04em',
        display: 'flex',
        alignItems: 'center',
        gap: 12,
      }}>
        <span style={{ fontSize: 16 }}>⚠</span>
        DEV SPIKE — NOT FOR PRODUCTION — @cantoo/pdf-lib v2.7 evaluation
        <span style={{ fontWeight: 400, opacity: 0.8 }}>
          {acroformSource === 'loading' && '(Loading sample PDFs…)'}
          {acroformSource === 'real-irs' && '| AcroForm: real IRS W-9 (fetched from /spike/fw9-fillable.pdf)'}
          {acroformSource === 'synthetic' && '| AcroForm: SYNTHETIC stand-in (real IRS W-9 unavailable — see notes)'}
        </span>
      </div>

      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '24px 16px' }}>

        {/* ── Intro ──────────────────────────────────────────────────────── */}
        <div style={{ background: '#fff', borderRadius: 8, padding: 16, marginBottom: 24, border: '1px solid #e0ddd8', fontSize: 13, color: '#44403c' }}>
          <strong>Purpose:</strong> Empirically validate @cantoo/pdf-lib as the P3 PDF engine before committing the migration.
          Three independent tests: (A) AcroForm fill+flatten fidelity, (B) free-position text overlay with documented coordinate transform,
          (C) photo embed. Each test produces a downloadable output PDF for off-device inspection.
          <br />
          <strong>Pass criteria:</strong> (A) field text visible after flatten with no layout breaks; (B) tapped text lands at the tapped position ±2pt;
          (C) photo fills the PDF page at correct aspect ratio.
        </div>

        {/* ── TEST A: AcroForm ─────────────────────────────────────────── */}
        <Section label="A" title="AcroForm Fill + Flatten">
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
            <PdfPreviewCard
              label={`INPUT — ${acroformSource === 'real-irs' ? 'Real IRS W-9' : 'Synthetic AcroForm'}`}
              labelColor={acroformSource === 'real-irs' ? '#14532d' : '#78350f'}
              blobUrl={acroformViewUrl}
            />
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <div style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: 6, padding: 10 }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: '#166534', marginBottom: 6 }}>Fields detected ({acroFieldNames.length})</div>
                {acroFieldNames.length === 0
                  ? <div style={{ fontSize: 11, color: '#6b7280' }}>Loading…</div>
                  : acroFieldNames.map(n => <div key={n} style={{ fontSize: 11, fontFamily: 'monospace', color: '#1e3a5f', marginBottom: 2 }}>{n}</div>)
                }
              </div>
              <button
                onClick={handleAcroFill}
                disabled={acroFillRunning || !acroformPdfBytes}
                style={btnStyle('#4a5d23', acroFillRunning || !acroformPdfBytes)}
              >
                {acroFillRunning ? 'Running…' : 'Fill first 2 fields + flatten()'}
              </button>
              {acroFillError && <div style={{ fontSize: 11, color: '#b91c1c' }}>Error: {acroFillError}</div>}
              {acroFillResult && (
                <>
                  <PdfPreviewCard label="OUTPUT — after flatten()" labelColor="#1e3a8a" blobUrl={acroFillViewUrl} />
                  <button
                    onClick={() => downloadPdf(acroFillResult, 'spike-acroform-flattened.pdf')}
                    style={btnStyle('#1e3a8a', false)}
                  >
                    Download flattened PDF
                  </button>
                  <div style={{ fontSize: 11, color: '#166534' }}>
                    Inspect: field text should be permanently baked into page; no interactive fields in output.
                  </div>
                </>
              )}
            </div>
          </div>
        </Section>

        {/* ── TEST B: Free-position overlay ─────────────────────────────── */}
        <Section label="B" title="Free-Position Text Overlay + Coordinate Transform">
          <div style={{ marginBottom: 10, fontSize: 12, color: '#44403c', background: '#fef3c7', border: '1px solid #fde68a', borderRadius: 6, padding: 8 }}>
            <strong>Formula:</strong> pdfX = cssX / scale &nbsp;|&nbsp; pdfY = pdfPageHeight − (cssY / scale)
            &nbsp;|&nbsp; scale = canvasCSSWidth / pdfPageWidth &nbsp;|&nbsp; DPR does NOT affect CSS pixel coordinates.
          </div>
          <div style={{ display: 'flex', gap: 12, marginBottom: 12, alignItems: 'center', flexWrap: 'wrap' }}>
            <input
              type="text"
              value={pendingOverlayText}
              onChange={e => setPendingOverlayText(e.target.value)}
              placeholder="Text to place"
              style={{ padding: '6px 10px', borderRadius: 4, border: '1px solid #d4d0ca', fontSize: 12, width: 180 }}
            />
            <button
              onClick={() => setOverlayPlacementMode(p => !p)}
              style={btnStyle(overlayPlacementMode ? '#b45309' : '#4a5d23', false)}
            >
              {overlayPlacementMode ? 'Cancel placement mode' : 'Enter placement mode — then tap PDF'}
            </button>
            <button
              onClick={() => setOverlayPoints([])}
              disabled={overlayPoints.length === 0}
              style={btnStyle('#7c1d1d', overlayPoints.length === 0)}
            >
              Clear points ({overlayPoints.length})
            </button>
            <button
              onClick={handleOverlayExport}
              disabled={overlayRunning || overlayPoints.length === 0 || !flatPdfBytes}
              style={btnStyle('#1e3a8a', overlayRunning || overlayPoints.length === 0 || !flatPdfBytes)}
            >
              {overlayRunning ? 'Exporting…' : 'Export PDF with overlay'}
            </button>
          </div>
          {overlayPlacementMode && (
            <div style={{ fontSize: 12, color: '#92400e', marginBottom: 8 }}>
              PLACEMENT MODE ACTIVE — tap anywhere on the PDF below to place &ldquo;{pendingOverlayText}&rdquo;
            </div>
          )}
          {transformDebug && (
            <div style={{ background: '#f0f4ff', border: '1px solid #c7d2fe', borderRadius: 6, padding: 8, marginBottom: 10, fontSize: 11, fontFamily: 'monospace' }}>
              <div style={{ fontWeight: 600, marginBottom: 4, fontSize: 11 }}>Last transform values (on-device debuggable)</div>
              <div>rawClick: ({transformDebug.rawClickX}, {transformDebug.rawClickY}) CSS px</div>
              <div>scale: {transformDebug.scale} &nbsp; dpr: {transformDebug.dpr} &nbsp; pdfPage: {transformDebug.pdfPageWidth}×{transformDebug.pdfPageHeight}</div>
              <div style={{ color: '#1e3a8a', fontWeight: 600 }}>→ pdfX: {transformDebug.pdfX} &nbsp; pdfY: {transformDebug.pdfY}</div>
            </div>
          )}
          <div style={{ display: 'grid', gridTemplateColumns: flatPageDims ? '1fr 1fr' : '1fr', gap: 16 }}>
            <div>
              <div style={{ fontSize: 11, color: '#6b7280', marginBottom: 4 }}>INPUT (flat PDF — tap to place text)</div>
              <div
                ref={flatPageRef}
                onClick={handleFlatCanvasClick}
                style={{
                  position: 'relative',
                  cursor: overlayPlacementMode ? 'crosshair' : 'default',
                  userSelect: 'none',
                  border: overlayPlacementMode ? '2px solid #f59e0b' : '1px solid #e0ddd8',
                  borderRadius: 4,
                  overflow: 'hidden',
                  display: 'inline-block',
                }}
              >
                {flatViewUrl ? (
                  <Document file={flatViewUrl} loading={<div style={{ padding: 40, color: '#9ca3af' }}>Loading PDF…</div>}>
                    <Page
                      pageNumber={1}
                      width={480}
                      onLoadSuccess={({ width, height }) => {
                        const el = flatPageRef.current
                        if (!el) return
                        const rect = el.getBoundingClientRect()
                        setFlatPageDims({ cssWidth: rect.width, cssHeight: rect.height, pdfWidth: width, pdfHeight: height })
                      }}
                    />
                  </Document>
                ) : (
                  <div style={{ padding: 40, color: '#9ca3af' }}>Loading…</div>
                )}
                {/* Overlay dot markers */}
                {overlayPoints.map((pt, i) => (
                  <div
                    key={i}
                    style={{
                      position: 'absolute',
                      left: pt.cssX,
                      top: pt.cssY,
                      transform: 'translate(-50%, -50%)',
                      width: 8,
                      height: 8,
                      borderRadius: '50%',
                      background: '#1d4ed8',
                      border: '2px solid #fff',
                      pointerEvents: 'none',
                    }}
                    title={`"${pt.text}" @ css(${Math.round(pt.cssX)},${Math.round(pt.cssY)})`}
                  />
                ))}
              </div>
            </div>
            {overlayResult && (
              <div>
                <div style={{ fontSize: 11, color: '#1e3a8a', marginBottom: 4 }}>OUTPUT (text burned in)</div>
                <PdfPreviewCard label="" labelColor="#1e3a8a" blobUrl={overlayViewUrl} />
                <button
                  onClick={() => downloadPdf(overlayResult, 'spike-overlay-text.pdf')}
                  style={{ ...btnStyle('#1e3a8a', false), marginTop: 8 }}
                >
                  Download overlay PDF
                </button>
                <div style={{ fontSize: 11, color: '#166534', marginTop: 6 }}>
                  Inspect: blue text should appear at the same position as the blue dots on the input.
                </div>
              </div>
            )}
          </div>
          {overlayError && <div style={{ fontSize: 11, color: '#b91c1c', marginTop: 8 }}>Error: {overlayError}</div>}
        </Section>

        {/* ── TEST C: Image embed ──────────────────────────────────────────── */}
        <Section label="C" title="Photo Embed (embedJpg / embedPng → drawImage)">
          <div style={{ marginBottom: 8, fontSize: 12, color: '#44403c' }}>
            Take a photo or select an image file. The spike embeds it into a new single-page PDF sized to US Letter.
          </div>
          <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap', marginBottom: 12 }}>
            <label style={{
              padding: '6px 14px',
              background: '#4a5d23',
              color: '#fff',
              borderRadius: 4,
              cursor: 'pointer',
              fontSize: 12,
              fontWeight: 500,
            }}>
              Choose / Capture Image
              <input
                type="file"
                accept="image/*"
                capture="environment"
                onChange={handleImageFile}
                style={{ display: 'none' }}
              />
            </label>
            {imageEmbedRunning && <span style={{ fontSize: 12, color: '#78350f' }}>Embedding…</span>}
          </div>
          {imageEmbedError && <div style={{ fontSize: 11, color: '#b91c1c', marginBottom: 8 }}>Error: {imageEmbedError}</div>}
          {(imagePreviewUrl || imageEmbedResult) && (
            <div style={{ display: 'grid', gridTemplateColumns: imagePreviewUrl ? '1fr 1fr' : '1fr', gap: 16 }}>
              {imagePreviewUrl && (
                <div>
                  <div style={{ fontSize: 11, color: '#6b7280', marginBottom: 4 }}>Input image (browser preview)</div>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={imagePreviewUrl} alt="Selected image" style={{ maxWidth: '100%', maxHeight: 400, objectFit: 'contain', border: '1px solid #e0ddd8', borderRadius: 4 }} />
                </div>
              )}
              {imageEmbedResult && (
                <div>
                  <div style={{ fontSize: 11, color: '#1e3a8a', marginBottom: 4 }}>OUTPUT PDF (image embedded)</div>
                  <PdfPreviewCard label="" labelColor="#1e3a8a" blobUrl={URL.createObjectURL(new Blob([toPlainUint8Array(imageEmbedResult)], { type: 'application/pdf' }))} />
                  <button
                    onClick={() => downloadPdf(imageEmbedResult, 'spike-image-embed.pdf')}
                    style={{ ...btnStyle('#1e3a8a', false), marginTop: 8 }}
                  >
                    Download image PDF
                  </button>
                  <div style={{ fontSize: 11, color: '#166534', marginTop: 6 }}>
                    Inspect: photo should fill page at correct aspect ratio; no stretching.
                  </div>
                </div>
              )}
            </div>
          )}
        </Section>

        {/* ── Notes ─────────────────────────────────────────────────────── */}
        <Section label="" title="Sample PDF Notes">
          <div style={{ fontSize: 12, lineHeight: 1.7 }}>
            <p><strong>AcroForm sample:</strong> {acroformSource === 'real-irs'
              ? 'Real IRS W-9 loaded from /spike/fw9-fillable.pdf (manually placed; see docs/pdf-spike-notes.md).'
              : 'SYNTHETIC — generated at runtime by @cantoo/pdf-lib because /spike/fw9-fillable.pdf was not found. Download the real IRS W-9 from https://www.irs.gov/pub/irs-pdf/fw9.pdf and place it at apps/web/public/spike/fw9-fillable.pdf for a higher-fidelity test.'
            }</p>
            <p><strong>Flat sample:</strong> SYNTHETIC — generated at runtime. Includes a coordinate grid at 50-pt intervals for visual alignment verification.</p>
            <p><strong>Coordinate transform (Test B):</strong> pdfX = cssX / scale; pdfY = pdfH − cssY / scale; where scale = canvasCSSWidth / pdfPageWidth. DPR does not appear in the formula because getBoundingClientRect() returns CSS pixels already abstracted from DPR.</p>
            <p><strong>Gate question:</strong> If (A) flatten is faithful, (B) text lands ±2pt of tap, and (C) image embed is clean — @cantoo/pdf-lib is confirmed for P3 migration and existing pdf-lib@1.17.1 can be removed.</p>
          </div>
        </Section>

      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------
function Section({ label, title, children }: { label: string; title: string; children: React.ReactNode }) {
  return (
    <div style={{ background: '#fff', borderRadius: 8, padding: 20, marginBottom: 20, border: '1px solid #e0ddd8' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, marginBottom: 14 }}>
        {label && (
          <div style={{ background: '#4a5d23', color: '#fff', borderRadius: 4, padding: '2px 8px', fontSize: 11, fontWeight: 700 }}>
            TEST {label}
          </div>
        )}
        <h2 style={{ margin: 0, fontSize: 15, fontWeight: 600, color: '#1c1917' }}>{title}</h2>
      </div>
      {children}
    </div>
  )
}

function PdfPreviewCard({ label, labelColor, blobUrl }: { label: string; labelColor: string; blobUrl: string }) {
  if (!blobUrl) {
    return <div style={{ border: '1px solid #e0ddd8', borderRadius: 4, padding: 40, color: '#9ca3af', fontSize: 12 }}>Loading…</div>
  }
  return (
    <div>
      {label && <div style={{ fontSize: 11, color: labelColor, marginBottom: 4, fontWeight: 500 }}>{label}</div>}
      <Document file={blobUrl} loading={<div style={{ padding: 40, color: '#9ca3af' }}>Loading PDF preview…</div>}>
        <Page pageNumber={1} width={480} />
      </Document>
    </div>
  )
}

function btnStyle(bg: string, disabled: boolean): React.CSSProperties {
  return {
    padding: '7px 14px',
    background: disabled ? '#9ca3af' : bg,
    color: '#fff',
    border: 'none',
    borderRadius: 4,
    cursor: disabled ? 'not-allowed' : 'pointer',
    fontSize: 12,
    fontWeight: 500,
  }
}
