// apps/web/src/lib/event-registry.ts
//
// Closed vocabulary for first-party telemetry. FEED keeps its logs on its own
// infrastructure (the Supabase `app_logs` table); this registry is the contract
// for what a browser may write there through /api/client-log.
//
//   event name -> the label keys that event may carry
//
// The route rejects an event name that is not a key here, drops any label key
// not listed for that event, and keeps the standard error fields
// (ERROR_LABEL_KEYS) only on error-level rows, with error_message capped at
// MAX_ERROR_MESSAGE_LEN characters.
//
// Sourcing: every event name the app emits — the static name argument of every
// logger.debug/info/warn/error, withMetric (as `<op>.complete` / `<op>.error`),
// privilegedRpc / privilegedFetch op and logEvent call in apps/web/src — plus
// every DISTINCT event seen in production app_logs over the trailing 30 days.
// Label keys come from the same call sites plus the production context keys,
// minus free-text and personal fields (user ids, emails, addresses, viewport
// bounds, file paths, raw query text, raw error text outside error_message).
// Events whose subject is a person (admin.user.*, admin.tier.set*, admin.notes.*,
// admin.denied, admin.audit.*) carry no target_id: their request_id joins to the
// durable admin_actions row, which already records the target.
// src/lib/__tests__/event-registry.test.ts re-scans the source on every run and
// fails when an emitted event is missing from this list.
//
// Adding an event: add `'<name>': ['label', ...]` here in the same PR that first
// emits it.

import { MAX_ERROR_MESSAGE_LEN } from './with-metric-core.mjs'

/** Error fields every error-level row may carry (set by logger.error / withMetric). */
const ERROR_LABEL_KEYS = ['error_code', 'error_name', 'error_message'] as const

export const EVENT_REGISTRY: Readonly<Record<string, readonly string[]>> = {
  '[admin:overview] admin_add_user_note': [],
  '[admin:overview] admin_delete_user_note': ['noteId'],
  '[admin:overview] admin_get_user_notes': ['count'],
  '[admin:overview] admin_list_users': ['count'],
  '[admin:overview] ban_toggle error': [],
  '[admin:overview] ban_toggle failed': [],
  '[admin:overview] ban_toggle success': ['action'],
  '[admin:overview] dashboard_completed_profiles error': [],
  '[admin:overview] delete_user error': [],
  '[admin:overview] delete_user failed': [],
  '[admin:overview] delete_user success': [],
  '[admin:users] delete_user failed': [],
  'a11y.pref.changed': ['enabled', 'pref'],
  'admin.audit.write_failed': [],
  'admin.business.approve': ['org_id', 'outcome'],
  'admin.business.approve.complete': ['action', 'request_id', 'target_id'],
  'admin.business.approve.error': ['action', 'request_id', 'target_id'],
  'admin.business.reject': ['org_id', 'outcome'],
  'admin.business.reject.complete': ['action', 'request_id', 'target_id'],
  'admin.business.reject.error': ['action', 'request_id', 'target_id'],
  'admin.business.set_active': ['active', 'org_id', 'outcome'],
  'admin.business.update': ['org_id', 'outcome'],
  'admin.check.failed': ['code'],
  'admin.checkin.kiosk.confirm': ['method', 'occurrence_id'],
  'admin.checkin.kiosk.walkin': ['household_size', 'occurrence_id'],
  'admin.community.tab.viewed': ['org_id'],
  'admin.denied': ['action', 'code', 'request_id'],
  'admin.error.boundary': ['digest', 'surface'],
  'admin.event.add_dates.complete': ['date_count', 'event_id', 'org_id', 'request_id'],
  'admin.event.add_dates.error': ['date_count', 'event_id', 'org_id', 'request_id'],
  'admin.event.attendance.load_failed': ['code'],
  'admin.event.create.complete': ['announce_days_before', 'event_type', 'frequency', 'location_source', 'org_id', 'request_id', 'series_end'],
  'admin.event.create.error': ['announce_days_before', 'event_type', 'frequency', 'location_source', 'org_id', 'request_id', 'series_end'],
  'admin.event.ending_soon.load_failed': ['code', 'org_id'],
  'admin.event.extend_series.complete': ['event_id', 'org_id', 'request_id'],
  'admin.event.extend_series.error': ['event_id', 'org_id', 'request_id'],
  'admin.event.preview.complete': ['frequency', 'org_id'],
  'admin.event.preview.error': ['frequency', 'org_id'],
  'admin.event.scheduler.kiosk_opened': ['event_id', 'occurrence_id'],
  'admin.event.scheduler.load_failed': ['code', 'scoped'],
  'admin.event.update.complete': ['action', 'announce_days_before', 'cleared_count', 'event_id', 'frequency', 'location_source', 'org_id', 'request_id', 'rule_edit', 'series_end'],
  'admin.event.update.error': ['action', 'announce_days_before', 'cleared_count', 'event_id', 'frequency', 'location_source', 'org_id', 'request_id', 'rule_edit', 'series_end'],
  'admin.form_template.approve.complete': ['action', 'request_id', 'target_id'],
  'admin.form_template.approve.error': ['action', 'request_id', 'target_id'],
  'admin.hours.invalid': ['kind'],
  'admin.nav.back_to_feed': ['source'],
  'admin.nav.member_view': ['kind', 'source', 'view'],
  'admin.notes.add.complete': ['request_id'],
  'admin.notes.add.error': ['request_id'],
  'admin.notes.delete.complete': ['request_id'],
  'admin.notes.delete.error': ['request_id'],
  'admin.notes.get.complete': ['request_id'],
  'admin.notes.get.error': ['request_id'],
  'admin.occurrence.cancel.complete': ['event_id', 'occurrence_id', 'org_id', 'request_id'],
  'admin.occurrence.cancel.error': ['event_id', 'occurrence_id', 'org_id', 'request_id'],
  'admin.org.duplicate_warning': ['action'],
  'admin.org.panel.close': ['dirty_fields', 'duration_ms', 'kind', 'mode', 'result', 'save_attempts'],
  'admin.org.save.complete': ['hours_count', 'location_op', 'mode', 'org_type', 'photo_count', 'request_id', 'resource_count', 'target_id'],
  'admin.org.save.error': ['hours_count', 'location_op', 'mode', 'org_type', 'photo_count', 'request_id', 'resource_count', 'target_id'],
  'admin.org.set_active.complete': ['active', 'request_id', 'target_id'],
  'admin.org.set_active.error': ['active', 'request_id', 'target_id'],
  'admin.org_page.load.complete': ['org_id', 'outcome', 'reason'],
  'admin.org_page.load.error': ['org_id', 'outcome', 'reason'],
  'admin.overview.list_users_failed': [],
  'admin.overview.loaded': ['duration_ms', 'org_id', 'suppressed'],
  'admin.people.list_failed': ['code'],
  'admin.post.authorize.complete': ['action', 'request_id', 'target_id'],
  'admin.post.authorize.error': ['action', 'request_id', 'target_id'],
  'admin.post.hold.complete': ['action', 'request_id', 'target_id'],
  'admin.post.hold.error': ['action', 'request_id', 'target_id'],
  'admin.post.remove.complete': ['action', 'request_id', 'target_id'],
  'admin.post.remove.error': ['action', 'request_id', 'target_id'],
  'admin.report.resolve.complete': ['action', 'request_id', 'target_id'],
  'admin.report.resolve.error': ['action', 'request_id', 'target_id'],
  'admin.resource.address_autocomplete.error': [],
  'admin.resource.approve': ['content_type', 'outcome', 'resource_id'],
  'admin.resource.approve.complete': ['action', 'request_id', 'target_id'],
  'admin.resource.approve.error': ['action', 'request_id', 'target_id'],
  'admin.resource.autocomplete': ['outcome', 'query_len', 'result_count', 'selected_index', 'suggest_latency_ms'],
  'admin.resource.geocode': ['address_changed', 'feature_count', 'geocode_latency_ms', 'geocoded', 'outcome', 'query_len', 'reason', 'resource_id', 'service_mode', 'source', 'tier'],
  'admin.resource.link.visit': ['resource_id'],
  'admin.resource.list': ['count', 'state'],
  'admin.resource.list.more': ['added', 'offset'],
  'admin.resource.map.expand': ['mappable', 'online_excluded', 'total'],
  'admin.resource.reject': ['outcome', 'resource_id'],
  'admin.resource.reject.complete': ['action', 'request_id', 'target_id'],
  'admin.resource.reject.error': ['action', 'request_id', 'target_id'],
  'admin.resource.update.complete': ['action', 'request_id', 'target_id'],
  'admin.resource.update.error': ['action', 'request_id', 'target_id'],
  'admin.safety_alert.remove.complete': ['action', 'request_id', 'target_id'],
  'admin.safety_alert.remove.error': ['action', 'request_id', 'target_id'],
  'admin.safety_alert.verify.complete': ['action', 'request_id', 'target_id'],
  'admin.safety_alert.verify.error': ['action', 'request_id', 'target_id'],
  'admin.shell.org_switch': ['org_id'],
  'admin.shell.tab_switch': ['from_tab', 'org_id', 'to_tab'],
  'admin.tier.check_failed': ['code'],
  'admin.tier.set': ['request_id', 'to'],
  'admin.tier.set.complete': ['action', 'request_id'],
  'admin.tier.set.error': ['action', 'request_id'],
  'admin.user.ban': ['actor_tier', 'ban_duration', 'outcome', 'request_id'],
  'admin.user.ban.complete': ['request_id'],
  'admin.user.ban.denied': ['actor_tier', 'code', 'outcome', 'request_id'],
  'admin.user.ban.error': ['request_id'],
  'admin.user.ban.failed': [],
  'admin.user.ban.target_lookup': ['not_found', 'request_id'],
  'admin.user.delete': ['actor_tier', 'outcome', 'request_id'],
  'admin.user.delete.complete': ['request_id'],
  'admin.user.delete.denied': ['actor_tier', 'code', 'outcome', 'request_id'],
  'admin.user.delete.error': ['request_id'],
  'admin.user.delete.failed': [],
  'admin.user.delete.target_lookup': ['not_found', 'request_id'],
  'admin.user.unban': ['actor_tier', 'ban_duration', 'outcome', 'request_id'],
  'admin.user.unban.complete': ['request_id'],
  'admin.user.unban.error': ['request_id'],
  'allow_messages.changed': ['allow_messages'],
  'allow_messages.read_failed': [],
  'allow_messages.write_failed': ['user_present'],
  'app.error.boundary': ['digest', 'surface'],
  'appreciation_give_failed': [],
  'appreciation_list_sent_failed': [],
  'appreciation_shelf_failed': [],
  'auth.getSession.timeout': [],
  'auth.ready': ['duration_ms', 'isAuthenticated'],
  'auth.record_attempt: audit_log insert failed (non-fatal)': [],
  'auth.safetyValve': ['bound_ms', 'totalWait_ms'],
  'auth.session.divergence': ['clientAnon'],
  'auth.signout': ['surface'],
  'auth.stateChange': ['event', 'hasSession'],
  'business.admin.list.fetch.complete': ['result_count'],
  'business.admin.list.fetch.error': ['result_count'],
  'business.admin.set_active.complete': ['active'],
  'business.admin.set_active.error': ['active'],
  'business.admin.update.complete': ['has_description', 'has_email', 'has_phone', 'has_website'],
  'business.admin.update.error': ['has_description', 'has_email', 'has_phone', 'has_website'],
  'business.hours.fetch.complete': ['result_count'],
  'business.hours.fetch.error': ['result_count'],
  'business.list.fetch.complete': ['result_count'],
  'business.list.fetch.error': ['result_count'],
  'business.pending.fetch.complete': ['result_count'],
  'business.pending.fetch.error': ['result_count'],
  'business.photo.upload.complete': ['image_type', 'size_bucket'],
  'business.photo.upload.error': ['image_type', 'size_bucket'],
  'business.photos.fetch.complete': ['result_count'],
  'business.photos.fetch.error': ['result_count'],
  'business.services.fetch.complete': ['result_count'],
  'business.services.fetch.error': ['result_count'],
  'business.submit.complete': ['attribute_count', 'gallery_count', 'has_cover', 'has_logo', 'has_social', 'has_website', 'hours_days_set', 'service_count'],
  'business.submit.error': ['attribute_count', 'gallery_count', 'has_cover', 'has_logo', 'has_social', 'has_website', 'hours_days_set', 'service_count'],
  'business.submit.failed': ['outcome'],
  'business.submit.pending': ['org_id', 'partial'],
  'chat.fetch.error': ['opId', 'status'],
  'chat.fetch.response': ['opId', 'status'],
  'chat.fetch.start': ['messageCount', 'opId'],
  'chat.request.completed': ['contentLength', 'didStream', 'duration_ms', 'model', 'opId'],
  'chat.request.failed': ['duration_ms', 'errorName', 'httpStatus', 'isAbort', 'opId', 'origin', 'retried'],
  'chat.request.retrying': ['duration_ms', 'errorName', 'httpStatus', 'opId'],
  'chat.send.start': ['flowType', 'messageCount', 'opId'],
  'chat.session.check': ['opId'],
  'chat.session.missing': ['opId'],
  'chat.session.result': ['hasSession', 'opId', 'tokenPresent'],
  'chat.stream.aborted': ['opId'],
  'chat.stream.firstChunk': ['duration_ms', 'opId'],
  'chat.stream.missingDone': ['contentLength', 'duration_ms', 'opId'],
  'chat.stream.nonStreamingFallback': ['opId'],
  'chat.stream.parseError': ['opId'],
  'chat.stream.start': ['opId'],
  'client.unhandled_rejection': ['kind'],
  'client.window.error': ['kind'],
  'conversations.request.blocked': ['outcome'],
  'conversations.request.complete': ['has_initial_message'],
  'conversations.request.error': ['has_initial_message'],
  'directory.picker.query.complete': ['filters', 'query_len_bucket', 'result_bucket'],
  'directory.picker.query.error': ['filters', 'query_len_bucket', 'result_bucket'],
  'document.annotations.decrypt.error': ['documentId'],
  'document.delete.error': ['documentId'],
  'document.upload.abort_treated_as_success': ['opId'],
  'document.upload.complete': ['annotation_count', 'durationMs', 'fileSizeBytes', 'hasAnnotations', 'opId'],
  'document.upload.error': ['category', 'durationMs', 'fileSizeBytes', 'opId'],
  'document.upload.start': ['category', 'encrypted', 'fileSizeBytes', 'opId'],
  'documents.annotations.update.complete': ['annotation_count', 'documentId'],
  'documents.annotations.update.error': ['annotation_count', 'documentId'],
  'documents.delete.error': ['id'],
  'documents.download.complete': ['documentId', 'has_annotations'],
  'documents.download.error': ['documentId', 'has_annotations'],
  'documents.download_for_edit.annotations': ['annotation_count', 'documentId', 'has_annotations'],
  'documents.download_for_edit.complete': ['documentId'],
  'documents.download_for_edit.error': ['documentId'],
  'documents.edit.open.annotations': ['annotation_count', 'documentId'],
  'documents.edit.open.complete': ['annotation_count', 'documentId'],
  'documents.edit.open.error': ['annotation_count', 'documentId'],
  'documents.move.error': ['category', 'id'],
  'documents.refresh.error': [],
  'documents.rename.encrypted.complete': ['documentId'],
  'documents.rename.encrypted.error': ['documentId'],
  'documents.update.error': ['id'],
  'documents.view.complete': ['documentId', 'flattened', 'has_annotations'],
  'documents.view.error': ['documentId', 'flattened', 'has_annotations'],
  'error_surface.shown': ['kind', 'locale', 'surface'],
  'events.checkin_state.load_failed': ['code', 'part', 'surface'],
  'events.next_date.load_failed': ['code', 'surface'],
  'events.tab.load.complete': ['limit'],
  'events.tab.load.error': ['limit'],
  'federation.sync.error': ['peerId'],
  'federation.sync.trigger_failed': ['peerId'],
  'federation.sync.triggered': ['peerId', 'result'],
  'federation.sync_data.fetch_failed': [],
  'federation.sync_logs.fetch_failed': [],
  'feed.like.toggle_failed': ['postId'],
  'feed.load.complete': ['has_geo', 'mode', 'page', 'page_size'],
  'feed.load.error': ['has_geo', 'mode', 'page', 'page_size'],
  'feed.optin.unblock': ['optInId'],
  'feed.optin.update': ['optInId', 'status'],
  'feed.post.create_failed': [],
  'feed.posts.fetch_failed': ['code', 'kind'],
  'feed.rank': ['has_geo', 'mode', 'returned_count'],
  'feed.rank.fetch_failed': ['code', 'kind'],
  'feed.realtime.hydrate_failed': ['postId'],
  'feed.realtime.insert.hydrate.empty': ['postId'],
  'feed.realtime.reconnect': ['channel', 'count', 'status'],
  'feed.realtime.subscribe.complete': ['channel'],
  'feed.realtime.subscribe.error': ['channel'],
  'feed.safety_alerts.fetch_failed': [],
  'forms.archive.complete': ['documentId', 'submissionId'],
  'forms.archive.warning': ['submissionId'],
  'forms.draft.complete': ['template_id'],
  'forms.draft.error': ['template_id'],
  'forms.pdf.save_initiated': ['annotation_count'],
  'forms.pdf.textbox_added': ['pageIndex', 'x', 'y'],
  'forms.submit.complete': ['has_signature', 'template_id'],
  'forms.submit.error': ['has_signature', 'template_id'],
  'forms.submit_direct.complete': ['has_signature', 'template_id'],
  'forms.submit_direct.error': ['has_signature', 'template_id'],
  'forms.wizard.draft_saved': ['step', 'templateId'],
  'forms.wizard.opened': ['templateId', 'total_steps'],
  'forms.wizard.step': ['direction', 'duration_ms', 'step', 'templateId', 'total_steps'],
  'forms.wizard.submit_error': ['step', 'templateId'],
  'forms.wizard.submitted': ['duration_ms', 'templateId'],
  'geo.fix.acquired': ['accuracy_bucket', 'duration_ms', 'source'],
  'geo.fix.error': [],
  'geo.notify.fanout': [],
  'geo.optin.toggled': ['enabled'],
  'geocode.resolve': ['outcome', 'source'],
  'global-error.boundary': ['digest', 'locale', 'surface'],
  'gov_forms.download.error': [],
  'hazard.geocode': ['accuracy', 'confidence', 'matched', 'ms', 'success'],
  'hazard.menu.open': ['type'],
  'hazard.pin.placed': ['severity', 'type'],
  'i18n.locale_resolved': ['locale', 'source'],
  'i18n.translation_fallback': ['key', 'locale'],
  'map.businesses_in_bounds.complete': ['limit'],
  'map.businesses_in_bounds.error': ['limit'],
  'map.geocode': ['cached', 'ms'],
  'map.geolocation.blocked': ['reason'],
  'map.geolocation.skipped': ['reason'],
  'map.orgs_in_bounds.complete': ['result_count'],
  'map.orgs_in_bounds.error': ['result_count'],
  'map.pins.rendered': ['approximate_pins', 'event', 'surface', 'tier_histogram', 'total_pins'],
  'map.resources_in_bounds.complete': ['category', 'limit'],
  'map.resources_in_bounds.error': ['category', 'limit'],
  'map.search.fly': ['result_count', 'zoom'],
  'map.snap_retailers_in_bounds.complete': ['limit'],
  'map.snap_retailers_in_bounds.error': ['limit'],
  'messages.send.complete': ['content_length'],
  'messages.send.error': ['content_length'],
  'my_badges_fetch_failed': [],
  'nav.alias.resolve': ['panel', 'subtab'],
  'nav.deeplink.resolve': ['kind', 'outcome', 'panel'],
  'nav.subtab.switch': ['panel', 'subtab'],
  'notif.pref.changed': ['application_updates', 'community_posts', 'resource_alerts'],
  'notif.pref.read_failed': [],
  'notif.pref.write_failed': ['user_present'],
  'oauth.callback.cookies': [],
  'oauth.callback.enter': ['hasCode', 'hasDescription', 'hasError', 'host'],
  'oauth.callback.exchange_failed': ['code', 'status'],
  'oauth.callback.exchange_ok': ['hasSession'],
  'oauth.callback.no_code': ['host'],
  'oauth.callback.no_session': ['hasUser'],
  'oauth.callback.provider_error': ['has_description', 'provider_error'],
  'oauth.callback.session_identity': ['isAnonymous'],
  'oauth.callback.unexpected': ['host'],
  'oauth.start': ['provider'],
  'oauth.start.error': ['provider'],
  'onboarding.complete.failed': ['step'],
  'onboarding.complete.no_user': ['authLoading'],
  'onboarding.complete.outer_abort': [],
  'onboarding.complete.pending_auth': [],
  'onboarding.complete.start': ['hasPhone'],
  'onboarding.complete.timeout': [],
  'onboarding.complete.verify_error': ['code'],
  'onboarding.complete.verify_failed': [],
  'onboarding.complete.verify_retry_failed': ['code'],
  'onboarding.location.resolved': ['hasState', 'source'],
  'onboarding.save.attempt': ['attempt', 'step'],
  'onboarding.save.exhausted': ['attempt', 'code', 'step'],
  'onboarding.save.failed': ['attempt', 'code', 'step'],
  'onboarding.save.ok': [],
  'onboarding.skip.no_user': ['authLoading'],
  'onboarding.skip.start': [],
  'org.photo.cleanup_failed': ['count'],
  'org.photo.upload.complete': ['image_type', 'size_bucket'],
  'org.photo.upload.error': ['image_type', 'size_bucket'],
  'org.read.by_id.complete': ['result_count'],
  'org.read.by_id.error': ['result_count'],
  'org.resources.fetch.complete': ['result_count'],
  'org.resources.fetch.error': ['result_count'],
  'org_admin.check.failed': ['code'],
  'organization.admin_detail.fetch.complete': ['result_count'],
  'organization.admin_detail.fetch.error': ['result_count'],
  'organization.list.fetch.complete': ['result_count'],
  'organization.list.fetch.error': ['result_count'],
  'organization.name_index.fetch.complete': ['result_count'],
  'organization.name_index.fetch.error': ['result_count'],
  'organization.roster.fetch.complete': ['result_count'],
  'organization.roster.fetch.error': ['result_count'],
  'organizations.list.failed': [],
  'panel.error.boundary': ['surface'],
  'pdf.autofill.complete': ['filled', 'total'],
  'pdf.autofill.error': [],
  'pdf.autofill.field': ['field', 'target'],
  'pdf.autofill.field.skip': ['field', 'reason'],
  'pdf.autofill.start': ['has_address'],
  'pdf.export_flattened.complete': ['annotation_count', 'source_bytes'],
  'pdf.export_flattened.error': ['annotation_count', 'source_bytes'],
  'pdf.export_flattened.pages': ['output_bytes', 'page_count'],
  'pdf.load.complete': ['byte_size'],
  'pdf.load.error': ['byte_size'],
  'pdf.prelock_flush.saved': ['annotation_count'],
  'pdf.render.error': ['byte_size'],
  'pdf.save.complete': ['annotation_count', 'byte_size'],
  'pdf.save.error': ['annotation_count', 'byte_size'],
  'pdf.viewer.error': ['byte_size'],
  'pdf.viewer.load': ['byte_size', 'duration_ms', 'page_count'],
  'petition.export': ['count', 'petitionId'],
  'petition.sign': ['petitionId'],
  'petition.sign.aborted': ['latencyMs', 'petitionId'],
  'petition.sign.attempt': ['petitionId'],
  'petition.sign.failed': [],
  'petition.sign.guest_blocked': ['latencyMs'],
  'petition.sign.route.ok': ['latencyMs', 'petitionId'],
  'petition.sign.success': ['count', 'latencyMs', 'petitionId'],
  'petition.sign.unauthorized': ['latencyMs'],
  'petition.sign.unexpected': [],
  'pin.clear': ['alertId'],
  'pin.confirm': ['alertId'],
  'pin.place': ['id', 'severity', 'type'],
  'pin.removed': ['alertId', 'request_id'],
  'pin.verified': ['alertId', 'request_id'],
  'poll.castVote.error': ['optionIndex', 'pollId'],
  'poll.castVote.success': ['optionIndex', 'pollId'],
  'poll.create.error': ['postId'],
  'poll.create.success': ['postId'],
  'poll.fetch.error': ['postId'],
  'poll.revokeVote.error': ['pollId'],
  'poll.revokeVote.success': ['pollId'],
  'poll.settleVotes.error': ['pollId'],
  'poll.vote.click': ['optionIndex', 'pollId'],
  'post.image.delete': [],
  'post.image.reencode': [],
  'post.image.upload': [],
  'post.image.upload.invoke': [],
  'programs.application.start': ['category', 'formTypes', 'programId'],
  'programs.categories.error': [],
  'programs.fetch.count': ['by_source', 'category', 'state', 'total'],
  'programs.fetch.error': [],
  'programs.filter': ['category', 'result_count'],
  'programs.panel.opened': [],
  'programs.program.expanded': ['category', 'programId'],
  'programs.program.saved': ['programId'],
  'programs.query.complete': ['category', 'has_search', 'state'],
  'programs.query.error': ['category', 'has_search', 'state'],
  'programs.share.error': [],
  'programs.share.success': ['programId'],
  'realtime-feed.subscribe.status': ['channel', 'status'],
  'request.error': ['digest', 'method', 'route', 'route_type'],
  'resource.set_location.complete': ['action', 'request_id', 'target_id'],
  'resource.set_location.error': ['action', 'request_id', 'target_id'],
  'safety-alerts.delete.error': [],
  'safety-alerts.delete.success': ['alertId'],
  'safety-alerts.fetch.error': [],
  'safety-alerts.place.error': [],
  'safety-alerts.update.error': [],
  'safety-alerts.update.success': ['alertId'],
  'safety-alerts.vote.error': [],
  'search.resources.complete': ['limit', 'surface'],
  'search.resources.error': ['limit', 'surface'],
  'search.resources.executed': ['result_count', 'surface'],
  'search.resources.timeout': ['surface'],
  'snap-retailers.fetch.error': [],
  'snap-retailers.fetch.resolved': ['count', 'result_count'],
  'snap-retailers.fetch.start': [],
  'snap-retailers.fetch.timeout': [],
  'vault.idleLock.failed': [],
  'vault.lock.failed': [],
  'vault.migration.failed': [],
  'vault.preLockFlush.failed': [],
  'vault.safetyValve': ['totalWait_ms'],
  'vault.status.check_failed': [],
  'vault.status.refresh_failed': [],
  'vault.unlock.complete': [],
  'vault.unlock.error': [],
  'viewport-businesses.fetch.error': [],
  'viewport-businesses.fetch.resolved': ['count', 'result_count'],
  'viewport-businesses.fetch.timeout': [],
  'viewport-organizations.fetch.error': [],
  'viewport-organizations.fetch.resolved': ['count', 'result_count'],
  'viewport-organizations.fetch.timeout': [],
  'viewport-resources.fetch.error': ['category'],
  'viewport-resources.fetch.resolved': ['category', 'count', 'result_count'],
  'viewport-resources.fetch.start': ['category'],
  'viewport-resources.fetch.timeout': ['category'],
  'wizard.complete': ['category', 'stepCount'],
  'wizard.start': ['category'],
  'wizard.submit.error': [],
}

type SanitizedEvent =
  | { ok: true; context: Record<string, string | number | boolean | null> }
  | { ok: false; reason: 'unknown_event' }

/**
 * Filter one event against the registry (used by /api/client-log AND the server sink). Unknown event -> rejected.
 * Known event -> only its registered label keys survive, values must be flat
 * primitives (strings capped at 200 chars), and the standard error fields are kept
 * only when `level` is 'error' (error_message capped at MAX_ERROR_MESSAGE_LEN).
 */
export function sanitizeClientEvent(
  event: string,
  level: 'info' | 'warn' | 'error',
  context: unknown
): SanitizedEvent {
  if (!Object.prototype.hasOwnProperty.call(EVENT_REGISTRY, event)) {
    return { ok: false, reason: 'unknown_event' }
  }
  const allowed = new Set<string>(EVENT_REGISTRY[event])
  if (level === 'error') ERROR_LABEL_KEYS.forEach((k) => allowed.add(k))

  const out: Record<string, string | number | boolean | null> = {}
  if (context && typeof context === 'object' && !Array.isArray(context)) {
    for (const [key, value] of Object.entries(context as Record<string, unknown>)) {
      if (!allowed.has(key)) continue
      if (typeof value === 'string') {
        out[key] = value.slice(0, key === 'error_message' ? MAX_ERROR_MESSAGE_LEN : 200)
      } else if (typeof value === 'number') {
        if (Number.isFinite(value)) out[key] = value
      } else if (typeof value === 'boolean' || value === null) {
        out[key] = value
      }
    }
  }
  return { ok: true, context: out }
}
